spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001
spring:
  application:
    name: STAR-PROVIDER #我注册的这个服务叫什么名字
  profiles: dev
eureka:
  client:
    service-url:
     defaultZone: http://localhost:7001/eureka  #服务注册的注册中心的地址
