spring:
  profiles:
    active:
    - dev

---
server:
  port: 8003
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: PRODUCT-SERVICE
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/legou
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
      view:
        suffix: .jsp
        prefix: /WEB-INF/views/
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8

eureka:
  client:
    service-url:
     defaultZone: http://localhost:7001/eureka


mybatis:
  type-aliases-package: com.cb.legou.domain,com.cb.legou.query


---

server:
  port: 8004
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: PRODUCT-SERVICE
  profiles: test
  datasource:
    url: jdbc:mysql://localhost:3306/legou
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
      view:
        suffix: .jsp
        prefix: /WEB-INF/views/
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8

eureka:
  client:
    service-url:
     defaultZone: http://localhost:7001/eureka


mybatis:
  type-aliases-package: com.cb.legou.domain,com.cb.legou.query
